INVOICE_FILE_DIR = r"/Users/dishantsethi/wofr/invoice_files"
INVOICE_BREAKDOWN_DIR = r"/Users/dishantsethi/wofr/invoice_breakdown_files"
MAPPING_FILE_DIR = r"/Users/dishantsethi/wofr/mapping_file"
SALES_INVOICE_DIR = r"/Users/dishantsethi/wofr/output_sales_invoice"
LOB_FILE_DIR = r"/Users/dishantsethi/wofr/LOB_file"